---
abstract: 'obtain files from a git repository before building a distribution'
author:
  - 'Jonathan Scott Duff <duff@pobox.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-GitObtain
requires:
  Dist::Zilla::Role::BeforeBuild: 0
  Dist::Zilla::Role::Plugin: 0
  File::Path: 2.08
  File::Spec::Functions: 0
  Git::Wrapper: 0
  Moose: 0
  namespace::autoclean: 0
version: 0.06
